[build]
  command = "NPM_CONFIG_PRODUCTION=false npm install && next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "space-store1.netlify.app"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_TYPESCRIPT_COMPILE_OPTIONS = "{}::{\"incremental\":true,\"target\":\"ES2017\"}"

# Prevent build failures
[build.processing]
  skip_processing = true

# Production context: all deploys from the main branch
[context.production]
  command = "NPM_CONFIG_PRODUCTION=false npm install && next build"

# Branch deploy context: Deploy preview for all branches
[context.branch-deploy]
  command = "NPM_CONFIG_PRODUCTION=false npm install && next build"

# Development branch specific settings
[context.development]
  command = "NPM_CONFIG_PRODUCTION=false npm install && next build"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

# Deploy preview specific settings
[context.deploy-preview]
  command = "NPM_CONFIG_PRODUCTION=false npm install && next build"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"