[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "space-store1.netlify.app"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_TYPESCRIPT_COMPILE_OPTIONS = "{}::{\"incremental\":true,\"target\":\"ES2017\"}"

# Prevent build failures
[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"